PHPの基礎2の課題完了
sanuki0679/php_exercise01 pull request #3
Opened 2022-12-27 08:18 UTC by sanuki0679

###
修正して再提出しました。

2022-12-27 08:33 UTC, kazu-taka commented on 03/06_array.php
> +echo $msg . PHP_EOL;
@sanuki0679 
こちらのファイルは不要(02/03_string2.phpと同一のため)となりますので、削除して下さい🙏

2022-12-28 08:07 UTC, kazu-taka requested changes
@sanuki0679 
一部修正お願いします🙇‍♂️

2022-12-28 08:07 UTC, kazu-taka commented on 03/02_array.php
> +var_dump($coffee) .PHP_EOL;
@sanuki0679 
`.PHP_EOL`は無くても良いです👍

2022-12-28 08:07 UTC, kazu-taka commented on 03/05_array.php
> +$club = XXXXX
@sanuki0679 
こちらのコードが出来ていないようなので、確認お願いします🙇‍♂️

2022-12-28 12:13 UTC, kazu-taka commented on 03/05_array.php
> +];
@sanuki0679 
$studyに直接連想配列を入れるのではなく、$lifeの中から`'study'`の部分だけを取り出してセットするように修正お願いします🙏
$clubの同様です✨

2022-12-29 12:54 UTC, kazu-taka requested changes
@sanuki0679 
確認しました✨

2022-12-29 12:54 UTC, kazu-taka commented on 03/05_array.php
> +];
@sanuki0679 
ここで配列を作り直して、echoの際に文字列を生成していますが、ここのタイミングで文字列を生成した方が良いと思います✨
```php
echo "私は、{$study}に力を入れて、学習をしています｡" . PHP_EOL ;
echo "また部活は、{$club}を兼部しています｡" . PHP_EOL;
```
上記のようなイメージです✨

2022-12-29 12:54 UTC, kazu-taka commented on 04/01_if.php
> +}
@sanuki0679 
インデントがずれているところがあるので、フォーマッターを使用してコードの整形をお願いします✨
フォーマッターはcommand + Sでファイルの保存をするタイミングで実行されます😊
他のファイルも整形お願いします🙏

2022-12-29 12:54 UTC, kazu-taka commented on 04/02_if.php
> +    echo 'は奇数です' .PHP_EOL;
@sanuki0679 
間違いではないですが、 `echo $point . 'は偶数です';`と1行にすることも可能です✨

2022-12-29 12:54 UTC, kazu-taka commented on 04/05_if.php
> +}
@sanuki0679 
整形してみました!
for文を2回使用していますが、1回でも可能ですので、チャレンジしてみてください✨
```php
<?php

echo '$numの値を入力して下さい: ';
$num = trim(fgets(STDIN));

// ここに処理を記述

for ($i = 1; $i <= $num; $i++) {

    $point = 0;

    for ($j = 1; $j <= $num; $j++) {
        if ($num % $j == 0) {
            $point += 1;
        }
    }

    if ($point == 2) {
        echo $num;
        echo ' は素数です。' . "\n";
        break;
    } else {
        echo $num;
        echo ' は素数ではありません。' . PHP_EOL;
        break;
    }
}
```

ヒントとしては、以下の通りです！
- $numが1の場合は素数ではないと判断する(フラグのような変数を用意して、素数フラグをfalseに設定)
- `for ($j = 1; $j <= $num; $j++) {`の部分を`for ($j = 2; $j <= $num; $j++) {`とする(1は素数ではないので、ループ対象から外す)
- for文の中で `if ($num % $j == 0) {`をやっていますが、割り切れた時点で素数と判断できるので、素数フラグをtrueにして、for文を抜ける

2023-01-06 02:18 UTC, sznr commented on 04/05_if.php
> +    echo 'は素数です。' . PHP_EOL;
$numが`1`のときに、`素数です`と出力されてしまうので、修正お願いします🙏

2023-01-06 03:43 UTC, sznr reviewed
条件は満たしているので課題はOKです😊

読みやすいコードを目指していくと更に良いと思います🙏✨
ひとつ解答例も載せておきます！

```php
<?php

echo '$numの値を入力して下さい: ';
$num = trim(fgets(STDIN));

$judge = True;

if ($num == 1) {
    $judge = False;
}

for ($i = 2; $i < $num; $i++) {
    if ($num % $i == 0) {
        $judge = False;
        break;
    }
}

if ($judge) {
    echo $num . 'は素数です。';
} else {
    echo $num . 'は素数ではありません。';
}
```

2023-01-06 03:43 UTC, sznr commented on 04/05_if.php
> +} elseif ($point == false) {
\nのところはPHP_EOL を使うと良いと思います😊

2023-01-06 04:01 UTC, merged

2023-01-06 04:03 UTC, sanuki0679 commented
### フォームの課題が完了したのでマージしました。